version: '3'
services:

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
      # - "443:443"
    volumes:
      - ./apps/lumen/:/var/www/lumen
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/conf.d/
    networks:
      - app-network

  lumen:
    build:
      context: apps/lumen
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: lumen
      SERVICE_TAGS: dev
    working_dir: /var/www/lumen
    volumes:
      - ./apps/lumen/:/var/www/lumen
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
      
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass nacharov
    volumes: 
      - cache:/data
      
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      
# Names our volume
volumes:
  my-db:
  cache:
    driver: local
    
networks:
  app-network:
    driver: bridge
